@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

CourseBook *-right-> "1" UniquePersonList
CourseBook *--> "1" Theme
UniquePersonList -right-> "*" Person

Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Address
Person *--> "0..1" Birthday
Person *--> "*" Tag
Person *--> "*" Course

Course *--> "1" CourseColor
@enduml
