@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedCourseBook" as VersionedCourseBook MODEL_COLOR
end box

[-> Model : undoCourseBook()
activate Model

Model -> VersionedCourseBook : undo()
activate VersionedCourseBook

VersionedCourseBook -> VersionedCourseBook :resetData(ReadOnlyCourseBook)
VersionedCourseBook --> Model :
deactivate VersionedCourseBook

Model -> VersionedCourseBook : redo()
activate VersionedCourseBook

VersionedCourseBook -> VersionedCourseBook :resetData(ReadOnlyCourseBook)
VersionedCourseBook --> Model :
deactivate VersionedCourseBook

[<-- Model
deactivate Model

@enduml
